# Generated by Django 5.1.4 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_drop_translated_base_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="canonical_url",
            field=models.URLField(blank=True, verbose_name="canonical URL"),
        ),
        migrations.AddField(
            model_name="page",
            name="noindex",
            field=models.BooleanField(default=False, verbose_name="hide from search engines"),
        ),
        migrations.AddField(
            model_name="page",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/", verbose_name="share image"
            ),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=200, verbose_name="meta description"),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="meta title"),
        ),
        migrations.AddField(
            model_name="post",
            name="canonical_url",
            field=models.URLField(blank=True, verbose_name="canonical URL"),
        ),
        migrations.AddField(
            model_name="post",
            name="noindex",
            field=models.BooleanField(default=False, verbose_name="hide from search engines"),
        ),
        migrations.AddField(
            model_name="post",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/", verbose_name="share image"
            ),
        ),
        migrations.AddField(
            model_name="posttranslation",
            name="meta_description",
            field=models.CharField(blank=True, max_length=200, verbose_name="meta description"),
        ),
        migrations.AddField(
            model_name="posttranslation",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="meta title"),
        ),
    ]
