# Generated by Django 5.1.4 on 2026-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_page_deleted_at_post_deleted_at_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-publish at this time. Keep the status as Draft until then.",
                null=True,
                verbose_name="scheduled for",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-publish at this time. Keep the status as Draft until then.",
                null=True,
                verbose_name="scheduled for",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-publish at this time. Keep the status as Draft until then.",
                null=True,
                verbose_name="scheduled for",
            ),
        ),
    ]
