# Generated by Django 5.1.4 on 2026-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Cmstack-Django", max_length=100, verbose_name="site name"
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200, verbose_name="tagline")),
                (
                    "posts_per_page",
                    models.PositiveIntegerField(default=10, verbose_name="posts per page"),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
