# Generated by Django 5.1.4 on 2026-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_active_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="allow_comments",
            field=models.BooleanField(default=True, verbose_name="allow comments"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="comments_require_login",
            field=models.BooleanField(default=False, verbose_name="require login to comment"),
        ),
    ]
