# Generated by Django 5.1.4 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "og_site_name",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to the site name when blank.",
                        max_length=100,
                        verbose_name="Open Graph site name",
                    ),
                ),
                (
                    "default_og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Used for Open Graph/Twitter when a page has no image of its own.",
                        null=True,
                        upload_to="seo/",
                        verbose_name="default share image",
                    ),
                ),
                (
                    "default_meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Fallback description for pages that don't set their own.",
                        max_length=200,
                        verbose_name="default meta description",
                    ),
                ),
                (
                    "twitter_handle",
                    models.CharField(
                        blank=True,
                        help_text="e.g. @yourbrand — used for twitter:site.",
                        max_length=40,
                        verbose_name="Twitter handle",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. G-XXXXXXXXXX",
                        max_length=20,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. GTM-XXXXXXX",
                        max_length=20,
                        verbose_name="Google Tag Manager ID",
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Google site verification"
                    ),
                ),
                (
                    "bing_site_verification",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bing site verification"
                    ),
                ),
                (
                    "discourage_search",
                    models.BooleanField(
                        default=False,
                        help_text="Adds a site-wide noindex,nofollow. Use for staging sites only.",
                        verbose_name="discourage search engines",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO settings",
                "verbose_name_plural": "SEO settings",
            },
        ),
    ]
