# Generated by Django 5.1.4 on 2026-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="organization_logo",
            field=models.ImageField(
                blank=True,
                help_text="Square-ish logo used in Organization structured data.",
                null=True,
                upload_to="seo/",
                verbose_name="organization logo",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="social_profiles",
            field=models.TextField(
                blank=True,
                help_text="One URL per line (Twitter, LinkedIn, …) — emitted as schema.org sameAs.",
                verbose_name="social profile URLs",
            ),
        ),
    ]
