# Generated by Django 5.1.4 on 2026-06-25 08:58

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0008_page_scheduled_at_post_scheduled_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Referenced in templates, e.g. “primary” or “footer”.",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "menu",
                "verbose_name_plural": "menus",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the linked item's title.",
                        max_length=80,
                        verbose_name="label",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom URL"),
                            ("post", "Post"),
                            ("page", "Page"),
                            ("category", "Category"),
                        ],
                        default="custom",
                        max_length=10,
                        verbose_name="links to",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=300, verbose_name="custom URL")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="position")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.category",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menus.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.page",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "menu item",
                "verbose_name_plural": "menu items",
                "ordering": ["position", "id"],
            },
            # MenuItem became translatable (parler) in 0003. TranslatableModel is
            # abstract (adds no columns), so declaring it here makes the historical
            # state translatable — required for 0003's MenuItemTranslation create.
            bases=(parler.models.TranslatableModel,),
        ),
    ]
