# Generated by Django 5.1.4 on 2026-06-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Nest this item under a top-level item (one level deep).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menus.menuitem",
            ),
        ),
    ]
